# Minimal Cloud Build pipeline: build image and deploy to Cloud Run
steps:
  - id: build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - --pull
      - -t
      - gcr.io/$PROJECT_ID/${_SERVICE_WEB}:${SHORT_SHA}
      - -f
      - Dockerfile
      - .

  - id: push
    waitFor: [build]
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/${_SERVICE_WEB}:${SHORT_SHA}

  - id: deploy
    waitFor: [push]
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_WEB}
      - --image=gcr.io/$PROJECT_ID/${_SERVICE_WEB}:${SHORT_SHA}
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --quiet

images:
  - gcr.io/$PROJECT_ID/${_SERVICE_WEB}:${SHORT_SHA}

substitutions:
  _SERVICE_WEB: notmytype
  _REGION: us-central1
