# Cloud Build pipeline: build & deploy the Next.js app to Cloud Run
# Required substitutions in the trigger:
#   _PROJECT_ID   (your GCP project id)
#   _REGION       (e.g., europe-north1)
#   _AR_REPO      (Artifact Registry repo name, e.g., typing-race)
#   _SERVICE_WEB  (Cloud Run service name, e.g., typing-race-web)
# Optional:
#   _MIN_INSTANCES (default 0)
#   _MAX_INSTANCES (default 10)
#   _KEEP_RELEASES (default 5)

steps:
  - id: 'build-web'
    waitFor: ['-']
    name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE_WEB}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE_WEB}:cache'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '--cache-from'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE_WEB}:cache'
      - 'web'

  - id: 'push-web'
    waitFor: ['build-web']
    name: 'gcr.io/cloud-builders/docker'
    args: ['push','${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE_WEB}:${SHORT_SHA}']

  - id: 'push-web-cache'
    waitFor: ['build-web']
    name: 'gcr.io/cloud-builders/docker'
    args: ['push','${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE_WEB}:cache']

  - id: 'deploy-web'
    waitFor: ['push-web']
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy ${_SERVICE_WEB} \
          --image=${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE_WEB}:${SHORT_SHA} \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --min-instances=${_MIN_INSTANCES:-0} \
          --max-instances=${_MAX_INSTANCES:-10}

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -euo pipefail
        keep_count=${_KEEP_RELEASES:-5}
        if [[ "$keep_count" -le 0 ]]; then
          echo "KEEP_RELEASES is $keep_count; skipping prune."
          exit 0
        fi
        image_path="${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE_WEB}"
        echo "Pruning $image_path, keeping $keep_count most recent images"
        tmp_file=$(mktemp)
        gcloud artifacts docker images list "$image_path" --sort-by="~UPDATE_TIME" --format="value(DIGEST)" > "$tmp_file"
        total_images=$(grep -c '.' "$tmp_file" || true)
        if [[ "$total_images" -le "$keep_count" ]]; then
          echo "Only $total_images images found, nothing to prune."
          rm -f "$tmp_file"
          exit 0
        fi
        tail -n "+$((keep_count+1))" "$tmp_file" | while read -r digest; do
          [[ -z "$digest" ]] && continue
          echo "Deleting $image_path@$digest"
          gcloud artifacts docker images delete "$image_path@$digest" --quiet --delete-tags || true
        done
        rm -f "$tmp_file"

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_AR_REPO}/${_SERVICE_WEB}:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
